"use client"

import { useMemo, useState } from "react"
import { MONTH_LABELS, sastYearMonth } from "../../lib/annualPlan.mjs"
import { PIPELINE_STAGES, SCENARIOS, summarizeCommercialModel } from "../../lib/annualCommercialPlan.mjs"

const money = (value) => value == null ? "—" : `R ${Math.round(Number(value)).toLocaleString("en-ZA")}`
const pct = (value) => value == null ? "—" : `${(value * 100).toFixed(1)}%`
const box = "w-full min-w-0 rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-sm outline-none focus:border-blue-500"
const card = "rounded-2xl border border-slate-200 bg-white p-5"
const label = "block text-[11px] font-bold text-slate-600"
const input = (value, onChange, options = {}) => <input className={box} type={options.type || "number"} min={options.min ?? "0"} step={options.step || "any"} disabled={options.disabled} value={value ?? ""} placeholder={options.placeholder || "—"} onChange={(event) => onChange(event.target.value === "" ? null : options.type === "text" ? event.target.value : Number(event.target.value))} />

function updateRow(rows, match, changes) {
  const index = rows.findIndex(match)
  if (index < 0) return [...rows, { ...changes }]
  return rows.map((row, i) => i === index ? { ...row, ...changes } : row)
}

function Headline({ title, value, sub }) {
  return <div className={card}><p className="text-xs font-bold text-slate-500">{title}</p><p className="mt-2 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{sub}</p></div>
}

export default function AnnualCommercialWorkspace({ plan, onChange, selectedMonth, onMonthChange }) {
  const [scenario, setScenario] = useState("management")
  const [detail, setDetail] = useState("products")
  const model = plan.commercialModel
  const report = useMemo(() => summarizeCommercialModel(model, plan), [model, plan])
  const setModel = (patch) => onChange({ ...model, ...patch })
  const setRow = (collection, match, changes) => setModel({ [collection]: updateRow(model[collection], match, changes) })
  const selectedLabel = MONTH_LABELS[selectedMonth]
  const now = sastYearMonth()
  const futureMonth = plan.year > now.year || plan.year === now.year && selectedMonth > now.month
  const target = report.managementTarget
  const forecast = report.forecastRevenue
  const gap = report.objectiveGap
  const scenarioReport = report.scenarios[scenario]

  if (!model) return <p className={card}>Commercial model is loading.</p>
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white px-5 py-3"><p className="text-xs font-bold text-slate-600">Edit monthly product, funnel and channel inputs for:</p><select className={box} aria-label="Commercial planning month" value={selectedMonth} onChange={(event) => onMonthChange(Number(event.target.value))}>{MONTH_LABELS.map((name, index) => <option key={name} value={index}>{name} {plan.year}</option>)}</select></div>
    <section className={card}>
      <p className="text-[10px] font-black uppercase tracking-[.18em] text-blue-700">{plan.year} commercial objective</p>
      <h2 className="mt-1 text-xl font-black">{plan.year} target and current forecast</h2>
      <p className="mt-1 text-xs text-slate-500">Product-built scenarios are planning assumptions. The management objective remains the annual turnover goal above. Forecast uses completed-month accounting actuals and explicitly entered future forecasts.</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Headline title="Base case · modelled" value={report.scenarios.base.modelled ? money(report.scenarios.base.revenue) : "Not modelled"} sub="Current channels and capacity" />
        <Headline title="Management target · objective" value={money(target)} sub={report.scenarios.management.modelled ? `Product-built: ${money(report.scenarios.management.revenue)}` : "Product mix not entered"} />
        <Headline title="Stretch / growth · modelled" value={report.scenarios.stretch.modelled ? money(report.scenarios.stretch.revenue) : "Not modelled"} sub="Upside requires stated drivers" />
        <Headline title="Current forecast" value={money(forecast)} sub={forecast == null ? `Incomplete · planning projection ${money(report.planningProjection)}` : `${report.forecastMonthsEntered}/12 months entered`} />
      </div>
      <div className="mt-3 grid gap-3 sm:grid-cols-3">
        <Headline title="Gap to management target" value={money(gap)} sub={gap == null ? "Enter all forecast or target months" : `${report.gapBasis} · ${pct(report.objectiveAchievement)} achieved`} />
        <Headline title="Product plan still unallocated" value={money(report.unassignedProductTarget)} sub="Management objective less product-built revenue" />
        <Headline title="Channel target still unallocated" value={money(report.unassignedChannelTarget)} sub="Management objective less growth-driver targets" />
      </div>
    </section>

    <nav aria-label="Commercial model sections" className="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-2">{[["products", "Products & scenarios"], ["channels", "Growth drivers"], ["pipeline", "Funnel & pipeline"], ["backlog", "Committed backlog"]].map(([key, name]) => <button key={key} onClick={() => setDetail(key)} className={`rounded-lg px-4 py-2 text-xs font-bold ${detail === key ? "bg-[#001d2e] text-white" : "text-slate-600 hover:bg-slate-100"}`}>{name}</button>)}</nav>

    <section className={card} hidden={detail !== "products"}>
      <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-black">Scenario & product plan</h2><p className="mt-1 text-xs text-slate-500">Enter monthly units, average selling price and average direct cost. Revenue and GP calculate from those inputs; neither is accounting actual.</p></div><div className="flex gap-2">{SCENARIOS.map((item) => <button key={item.key} onClick={() => setScenario(item.key)} className={`rounded-lg px-3 py-2 text-xs font-bold ${scenario === item.key ? "bg-[#001d2e] text-white" : "bg-slate-100 text-slate-600"}`}>{item.label}</button>)}</div></div>
      <div className="mt-4 max-w-[220px]"><label className={label}>Company-level target GP %{input(model.grossMarginTarget * 100, (value) => setModel({ grossMarginTarget: value == null ? 0.4 : Math.min(100, value) / 100 }), { step: "0.1" })}</label><p className="mt-1 text-[11px] text-slate-500">Used for the legacy monthly target proxy; product GP uses each category’s price and direct cost.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Headline title="Revenue · plan" value={scenarioReport.modelled ? money(scenarioReport.revenue) : "Not entered"} sub={`${scenarioReport.units} planned units`} /><Headline title="Gross profit · plan" value={scenarioReport.modelled ? money(scenarioReport.gp) : "—"} sub={`Weighted GP: ${pct(scenarioReport.margin)}`} /><Headline title="Operating profit · proxy" value={scenarioReport.modelled ? money(scenarioReport.operatingProfit) : "—"} sub={scenarioReport.operatingExpenses == null ? "Complete 12 months of fixed expenses" : "GP less annual fixed expenses"} /><Headline title="Average order value" value={money(scenarioReport.averageOrderValue)} sub="Product mix weighted" /></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1280px] text-left text-xs"><thead className="bg-slate-100"><tr>{["Product category", `${selectedLabel} units`, "Avg sell · R", "Avg direct cost · R", "Annual plan revenue", "Annual GP", "GP %", "Min GP %", "Lead time · days", "Sales cycle · days"].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody>{report.products.map((product) => {
        const row = model.productPlans.find((item) => item.productId === product.id && item.scenario === scenario && item.month === selectedMonth) || {}
        const set = (field, value) => setRow("productPlans", (item) => item.productId === product.id && item.scenario === scenario && item.month === selectedMonth, { productId: product.id, scenario, month: selectedMonth, [field]: value })
        const annual = product.scenarios[scenario]
        return <tr key={product.id} className="border-b align-top"><td className="px-2 py-2"><input aria-label={`Category name ${product.name}`} className={box} value={product.name} onChange={(event) => setModel({ products: model.products.map((item) => item.id === product.id ? { ...item, name: event.target.value } : item) })} /></td><td className="px-2 py-2">{input(row.units, (value) => set("units", value), { step: "1" })}</td><td className="px-2 py-2">{input(row.price, (value) => set("price", value))}</td><td className="px-2 py-2">{input(row.directCost, (value) => set("directCost", value))}</td><td className="px-2 py-3 font-bold">{money(annual.revenue)}</td><td className="px-2 py-3">{money(annual.gp)}</td><td className={`px-2 py-3 ${product.minimumMargin != null && annual.margin != null && annual.margin < product.minimumMargin ? "font-bold text-rose-700" : ""}`}>{pct(annual.margin)}</td><td className="px-2 py-2">{input(product.minimumMargin == null ? null : product.minimumMargin * 100, (value) => setModel({ products: model.products.map((item) => item.id === product.id ? { ...item, minimumMargin: value == null ? null : value / 100 } : item) }), { step: "0.1" })}</td><td className="px-2 py-2">{input(product.leadTimeDays, (value) => setModel({ products: model.products.map((item) => item.id === product.id ? { ...item, leadTimeDays: value } : item) }), { step: "1" })}</td><td className="px-2 py-2">{input(product.salesCycleDays, (value) => setModel({ products: model.products.map((item) => item.id === product.id ? { ...item, salesCycleDays: value } : item) }), { step: "1" })}</td></tr>
      })}</tbody></table></div>
      <button className="mt-3 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" onClick={() => setModel({ products: [...model.products, { id: crypto.randomUUID(), name: "New product category", minimumMargin: null, leadTimeDays: null, salesCycleDays: null }] })}>Add product category</button>
      <div className="mt-5 space-y-2"><h3 className="text-sm font-black">Revenue & product mix · {SCENARIOS.find((item) => item.key === scenario)?.label}</h3><p className="text-[11px] text-slate-500">Blue = planned share of revenue · Sky = allocated actual share</p>{report.products.filter((item) => item.scenarios[scenario].revenue > 0 || item.actual.revenue > 0).map((product) => <div key={product.id} className="grid grid-cols-[150px_1fr_1fr_90px] items-center gap-2 text-xs"><span className="truncate">{product.name}</span><div className="h-3 rounded bg-slate-100"><div className="h-3 rounded bg-blue-600" style={{ width: `${scenarioReport.revenue > 0 ? product.scenarios[scenario].revenue / scenarioReport.revenue * 100 : 0}%` }} /></div><div className="h-3 rounded bg-slate-100"><div className="h-3 rounded bg-sky-400" style={{ width: `${report.productActualRevenue > 0 ? product.actual.revenue / report.productActualRevenue * 100 : 0}%` }} /></div><strong className="text-right">{money(product.scenarios[scenario].revenue)}</strong></div>)}</div>
    </section>

    <section className={card} hidden={detail !== "products"}><h2 className="text-lg font-black">Actual product mix · management-entered</h2><p className="mt-1 text-xs text-slate-500">Allocate recognised accounting revenue and direct costs by product. These figures are separate from the accounting totals above; reconcile before using them externally.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[750px] text-left text-xs"><thead className="bg-slate-100"><tr>{["Product", `${selectedLabel} actual units`, "Recognised revenue · R", "Direct cost · R", "Annual actual GP", "Annual actual GP %"].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody>{report.products.map((product) => {
      const row = model.productActuals.find((item) => item.productId === product.id && item.month === selectedMonth) || {}
      const set = (field, value) => setRow("productActuals", (item) => item.productId === product.id && item.month === selectedMonth, { productId: product.id, month: selectedMonth, [field]: value })
      return <tr key={product.id} className="border-b"><th className="px-2 py-2">{product.name}</th><td className="px-2 py-2">{input(row.units, (value) => set("units", value), { step: "1", disabled: futureMonth })}</td><td className="px-2 py-2">{input(row.revenue, (value) => set("revenue", value), { disabled: futureMonth })}</td><td className="px-2 py-2">{input(row.directCost, (value) => set("directCost", value), { disabled: futureMonth })}</td><td className="px-2 py-2">{product.actual.hasData ? money(product.actual.gp) : "—"}</td><td className="px-2 py-2"><span className={product.minimumMargin != null && product.actual.margin != null && product.actual.margin < product.minimumMargin ? "font-bold text-rose-700" : ""}>{pct(product.actual.margin)}</span></td></tr>
    })}</tbody></table></div><p className={`mt-3 rounded-lg p-3 text-xs ${report.productRevenueReconciliation === 0 ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-900"}`}>Accounting actual revenue entered: {report.accountingActualMonths ? money(report.accountingActualRevenue) : "—"} · Allocated by product: {money(report.productActualRevenue)} · Unallocated / overallocated: {money(report.productRevenueReconciliation)}</p></section>

    <section className={card} hidden={detail !== "channels"}><h2 className="text-lg font-black">Growth drivers & revenue bridge</h2><p className="mt-1 text-xs text-slate-500">A product is what was sold; a channel is where the order came from. Channel targets must reconcile to the management objective. Actual channel revenue is entered separately and should reconcile to accounting actuals.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-xs"><thead className="bg-slate-100"><tr>{["Growth driver", `${SCENARIOS.find((item) => item.key === scenario)?.label} target · R`, `${selectedLabel} actual · R`, "Annual actual · R", "Weighted open pipeline", "Committed backlog", "Variance · R"].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody>{report.channels.map((channel) => {
      const targetRow = model.channelTargets.find((item) => item.channelId === channel.id && item.scenario === scenario)
      const actualRow = model.channelActuals.find((item) => item.channelId === channel.id && item.month === selectedMonth)
      return <tr key={channel.id} className="border-b"><td className="px-2 py-2"><input className={box} value={channel.name} onChange={(event) => setModel({ channels: model.channels.map((item) => item.id === channel.id ? { ...item, name: event.target.value } : item) })} /></td><td className="px-2 py-2">{input(targetRow?.revenue, (value) => setRow("channelTargets", (item) => item.channelId === channel.id && item.scenario === scenario, { channelId: channel.id, scenario, revenue: value }))}</td><td className="px-2 py-2">{input(actualRow?.revenue, (value) => setRow("channelActuals", (item) => item.channelId === channel.id && item.month === selectedMonth, { channelId: channel.id, month: selectedMonth, revenue: value }), { disabled: futureMonth })}</td><td className="px-2 py-2">{money(channel.actual)}</td><td className="px-2 py-2">{money(channel.weightedPipeline)}</td><td className="px-2 py-2">{money(channel.backlogRemaining)}</td><td className="px-2 py-2">{money(channel.actual != null && channel.targets[scenario] != null ? channel.actual - channel.targets[scenario] : null)}</td></tr>
    })}</tbody></table></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 text-sm font-bold"><span>Assigned channel target: {money(report.channels.reduce((total, item) => total + item.targets[scenario], 0))}</span>{scenario === "management" && <span className={report.unassignedChannelTarget > 0 ? "text-amber-700" : "text-slate-700"}>Unassigned management target: {money(report.unassignedChannelTarget)}</span>}</div><button className="mt-3 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" onClick={() => setModel({ channels: [...model.channels, { id: crypto.randomUUID(), name: "New growth driver" }] })}>Add growth driver</button><p className={`mt-3 rounded-lg p-3 text-xs ${report.channelRevenueReconciliation === 0 ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-900"}`}>Accounting actual revenue entered: {report.accountingActualMonths ? money(report.accountingActualRevenue) : "—"} · Allocated by channel: {money(report.channelActualRevenue)} · Unallocated / overallocated: {money(report.channelRevenueReconciliation)}</p></section>

    <section className={card} hidden={detail !== "pipeline"}><h2 className="text-lg font-black">Commercial funnel · {selectedLabel}</h2><p className="mt-1 text-xs text-slate-500">Enter measured monthly stage totals. Leave unavailable data blank; a blank is not zero.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["leads", "Leads generated"], ["qualified", "Qualified leads"], ["quotes", "Quotes issued"], ["quotedValue", "Quoted value · R"], ["negotiations", "Negotiations"], ["won", "Orders won"], ["wonValue", "Won order value · R"], ["salesCycleDays", "Avg sales cycle · days"]].map(([key, name]) => <label key={key} className={label}>{name}{input(model.funnel[selectedMonth]?.[key], (value) => setModel({ funnel: model.funnel.map((entry, index) => index === selectedMonth ? { ...entry, [key]: value } : entry) }), { disabled: futureMonth })}</label>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Headline title="Lead → won · count" value={pct(report.funnel[selectedMonth].conversionCount)} sub="Orders won / leads" /><Headline title="Quote → won · value" value={pct(report.funnel[selectedMonth].conversionValue)} sub="Won value / quoted value" /></div></section>

    <section className={card} hidden={detail !== "pipeline"}><h2 className="text-lg font-black">Open pipeline & coverage</h2><p className="mt-1 text-xs text-slate-500">Open opportunities are potential sales, not revenue. Probability weighting is a forecast aid. Signed orders belong in the backlog, never in the open pipeline.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Headline title="Unweighted pipeline" value={money(report.pipelineValue)} sub="Open opportunity value" /><Headline title="Weighted pipeline" value={money(report.weightedPipeline)} sub="Stage or entered probability" /><Headline title="Qualified pipeline" value={money(report.qualifiedPipeline)} sub="Early enquiries excluded" /><Headline title="Next 90-day coverage" value={report.pipelineCoverage == null ? "—" : `${report.pipelineCoverage.toFixed(1)}×`} sub={`${report.pipelineStatus} · ${money(report.next90QualifiedPipeline)} closing against ${money(report.next90Target)} target`} /></div><div className="mt-4 flex flex-wrap gap-3"><label className={label}>Watch threshold · ×{input(model.pipelineThresholds.amber, (value) => setModel({ pipelineThresholds: { ...model.pipelineThresholds, amber: value } }), { step: "0.1" })}</label><label className={label}>On-track threshold · ×{input(model.pipelineThresholds.green, (value) => setModel({ pipelineThresholds: { ...model.pipelineThresholds, green: value } }), { step: "0.1" })}</label></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-slate-100"><tr>{["Opportunity", "Product", "Channel", "Stage", "Value · R", "Probability %", "Expected close", ""].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody>{model.opportunities.map((item) => {
      const set = (changes) => setModel({ opportunities: model.opportunities.map((row) => row.id === item.id ? { ...row, ...changes } : row) })
      return <tr key={item.id} className="border-b"><td className="px-2 py-2">{input(item.name, (value) => set({ name: value }), { type: "text" })}</td><td className="px-2 py-2"><select className={box} value={item.productId} onChange={(event) => set({ productId: event.target.value })}>{model.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></td><td className="px-2 py-2"><select className={box} value={item.channelId} onChange={(event) => set({ channelId: event.target.value })}>{model.channels.map((channel) => <option key={channel.id} value={channel.id}>{channel.name}</option>)}</select></td><td className="px-2 py-2"><select className={box} value={item.stage} onChange={(event) => set({ stage: event.target.value })}>{PIPELINE_STAGES.map((stage) => <option key={stage.key} value={stage.key}>{stage.label}</option>)}</select></td><td className="px-2 py-2">{input(item.value, (value) => set({ value }))}</td><td className="px-2 py-2">{input(item.probability == null ? null : item.probability * 100, (value) => set({ probability: value == null ? null : value / 100 }), { step: "1" })}</td><td className="px-2 py-2"><select className={box} value={item.expectedCloseMonth} onChange={(event) => set({ expectedCloseMonth: Number(event.target.value) })}>{MONTH_LABELS.map((name, index) => <option key={name} value={index}>{name}</option>)}</select></td><td className="px-2 py-2"><button className="font-bold text-rose-700" onClick={() => setModel({ opportunities: model.opportunities.filter((row) => row.id !== item.id) })}>Remove</button></td></tr>
    })}</tbody></table></div><button className="mt-3 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" onClick={() => setModel({ opportunities: [...model.opportunities, { id: crypto.randomUUID(), name: "New opportunity", productId: model.products[0]?.id || "", channelId: model.channels[0]?.id || "", stage: "early", value: null, probability: null, expectedCloseMonth: selectedMonth }] })}>Add opportunity</button></section>

    <section className={card} hidden={detail !== "backlog"}><h2 className="text-lg font-black">Committed order book / backlog</h2><p className="mt-1 text-xs text-slate-500">Record accepted work that has not yet been recognised as accounting revenue. Remaining value = order value − recognised revenue. This is a management schedule; verify it against sales orders and invoices.</p><p className="mt-3 text-2xl font-black">{money(report.backlogValue)} <span className="text-xs font-normal text-slate-500">remaining committed value</span></p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-slate-100"><tr>{["Customer / project", "Product", "Channel", "Order value", "Recognised", "Remaining", "Expected GP", "Delivery", ""].map((name) => <th key={name} className="px-2 py-2">{name}</th>)}</tr></thead><tbody>{report.backlog.map((item) => {
      const set = (changes) => setModel({ backlog: model.backlog.map((row) => row.id === item.id ? { ...row, ...changes } : row) })
      return <tr key={item.id} className="border-b"><td className="px-2 py-2">{input(item.name, (value) => set({ name: value }), { type: "text" })}</td><td className="px-2 py-2"><select className={box} value={item.productId} onChange={(event) => set({ productId: event.target.value })}>{model.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></td><td className="px-2 py-2"><select className={box} value={item.channelId} onChange={(event) => set({ channelId: event.target.value })}>{model.channels.map((channel) => <option key={channel.id} value={channel.id}>{channel.name}</option>)}</select></td><td className="px-2 py-2">{input(item.orderValue, (value) => set({ orderValue: value }))}</td><td className="px-2 py-2">{input(item.recognizedRevenue, (value) => set({ recognizedRevenue: value }))}</td><td className="px-2 py-2 font-bold">{money(item.remaining)}</td><td className="px-2 py-2">{input(item.expectedGp, (value) => set({ expectedGp: value }))}</td><td className="px-2 py-2"><select className={box} value={item.deliveryMonth} onChange={(event) => set({ deliveryMonth: Number(event.target.value) })}>{MONTH_LABELS.map((name, index) => <option key={name} value={index}>{name}</option>)}</select></td><td className="px-2 py-2"><button className="font-bold text-rose-700" onClick={() => setModel({ backlog: model.backlog.filter((row) => row.id !== item.id) })}>Remove</button></td></tr>
    })}</tbody></table></div><button className="mt-3 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold" onClick={() => setModel({ backlog: [...model.backlog, { id: crypto.randomUUID(), name: "New committed order", productId: model.products[0]?.id || "", channelId: model.channels[0]?.id || "", orderValue: null, recognizedRevenue: null, expectedGp: null, deliveryMonth: selectedMonth }] })}>Add committed order</button></section>
    <p className="text-xs leading-5 text-slate-500">Source discipline: accounting actuals remain in Monthly inputs; product and channel allocations are management-entered; opportunities are uncommitted; backlog is committed but unrecognised. Unknown values remain blank.</p>
  </div>
}
