'use client'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { ATLAS_PRODUCT_RANGE, getAtlasProduct, withAtlasProduct } from '../../lib/atlasProductRange'
const families = [
  { name:'Warehouses', detail:'Modular warehouse structures. Choose your span to open its workspace.', codes:['W06','W08','W10','W12'] },
  { name:'Solar structures', detail:'Solar carports and ground-mounted panel structures.', codes:['SOLAR-CARPORT','GROUND-MOUNT'] },
  { name:'Carports', detail:'Covered parking structures.', codes:['CARPORT'] },
  { name:'Trusses & connections', detail:'Roof truss systems and the Atlas connection range.', codes:['TRUSS','BRACKETRY'] },
]
export default function AtlasProductHome() {
  const params=useSearchParams();const product=getAtlasProduct(params.get('product'))
  if(product && !product.available) return <div className="p-6"><h2 className="text-2xl font-bold">{product.name}</h2><p className="mt-3 text-slate-600">This product workspace has not yet been configured.</p><Link className="mt-5 inline-block font-bold text-blue-700" href="/os/atlas">Back to product families →</Link></div>
  if(product) {
    const warehouse=/^W\d{2}$/.test(product.code)
    return <div className="space-y-6 p-4 sm:p-6"><section className="rounded-2xl bg-[#001d2e] p-6 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-widest text-sky-200">Atlas system · {product.family}</p><h2 className="mt-4 text-3xl font-bold">{product.name}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">{product.summary}</p><div className="mt-6 flex flex-wrap gap-3"><Link href={withAtlasProduct(warehouse?'/os/atlas/pricing':'/os/atlas/solar-pricing',product.code)} className="rounded-lg bg-white px-5 py-3 text-sm font-bold text-blue-800">Configure {product.name} →</Link>{product.code==='W08'&&<Link href="/os/atlas/products?product=W08&view=technical" className="rounded-lg border border-white/30 px-5 py-3 text-sm font-bold">Controlled product sheet</Link>}</div></section><div className="grid gap-4 sm:grid-cols-3">{(warehouse?[['Span',`${Number(product.code.slice(1))}m`],['Construction','Modular bolted frame'],['Bay method','4m warehouse bays']]:[['Product','Solar Carport'],['Layouts','Single or double row'],['Configuration','Parking width and layout']]).map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-3 text-lg font-bold">{value}</p></div>)}</div><section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-bold">One product, connected information</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use the sections above to configure this product, inspect its material schedule and review technical information. Pricing uses the existing Atlas calculation engine. Product development status is shown separately from pricing availability.</p></section></div>
  }
  return <div className="p-4 sm:p-6"><header className="mb-6 rounded-2xl bg-[#001d2e] p-7 text-white"><p className="text-xs font-bold uppercase tracking-widest text-sky-200">Atlas product family</p><h1 className="mt-3 text-3xl font-bold">What are you working on?</h1><p className="mt-3 text-sm text-slate-300">Choose a family, then a product. Its specifications, schedules and pricing stay together.</p></header><div className="grid gap-5 lg:grid-cols-2">{families.map(family=><section key={family.name} className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">{family.name}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{family.detail}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{family.codes.map(code=>{const item=ATLAS_PRODUCT_RANGE.find(p=>p.code===code);return item.available?<Link key={code} href={withAtlasProduct('/os/atlas/products',code)} className="rounded-xl border border-blue-200 bg-blue-50 p-4 hover:border-blue-600"><p className="font-bold text-blue-900">{item.name} →</p><p className="mt-1 text-xs text-blue-700">{item.status}</p></Link>:<div key={code} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><p className="font-semibold text-slate-600">{item.name}</p><p className="mt-1 text-xs text-slate-500">Workspace not yet configured</p></div>})}</div></section>)}</div></div>
}
