import Image from 'next/image';
import Link from '../BuilderEntryLink';

const action = 'inline-flex min-h-12 items-center justify-center gap-4 bg-[#0043f3] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#07377d] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#0043f3]';
const label = 'font-mono text-xs uppercase tracking-[0.18em] text-[#0043f3]';
const products = [
  { code: 'W / 01', title: 'Modular steel warehouses', image: '/atlas_warehouse.webp', alt: 'Atlas warehouse steel rafters with bolted ridge connections', description: 'Storage, workshops and agricultural buildings. Configure an Atlas W-Series warehouse around standard spans and 4m building bays.', detail: '6m–15m spans / 4m bays', href: '/warehouse-builder', cta: 'Build a warehouse in 3D', product: '/products/cflc-diy-warehouse-kits', links: [['10m × 10m', '/warehouse-cost/10x10'], ['20m × 10m', '/warehouse-cost/20x10'], ['45m × 8m', '/warehouse-cost/45x8']] },
  { code: 'C / 02', title: 'Solar carport structures', image: '/solar_carport_hero.webp', alt: 'Steel solar carport structure over a parking area', description: 'Put your parking area to work. Explore parking bays and row layouts in 3D, check panel capacity and see a steel structure guide price.', detail: 'Parking layouts / Solar support', href: '/tools/solar-carport-estimator', cta: 'Build a solar carport in 3D', product: '/products/cflc-solar-carports', links: [['Steel carports', '/products/cflc-carport-kits'], ['Solar ground mounts', '/products/cflc-ground-mounts']] },
];

export default function HomepageSections({ questions }) {
  return <div className="bg-white text-[#001d2e]">
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24" aria-labelledby="atlas-range">
      <div className="grid gap-6 border-b border-[#cad9e2] pb-10 lg:grid-cols-[1.35fr_0.65fr] lg:items-end">
        <div><p className={label}>Atlas System / Developed by Smart Steel</p><h2 id="atlas-range" className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.06] tracking-tight sm:text-5xl lg:text-6xl">Your next structure.<br /><span className="text-[#0043f3]">Start with a clear plan.</span></h2></div>
        <p className="max-w-lg text-base leading-7 text-[#526878]">Steel building systems for South African sites. Choose your product, explore it in 3D and understand the supply scope before requesting a reviewed quote.</p>
      </div>
      <div className="mt-10 space-y-12 lg:space-y-16">
        {products.map((product, index) => <article key={product.code} className="grid gap-0 lg:grid-cols-2">
          <div className={`relative min-h-64 overflow-hidden bg-[#e6f0f5] sm:min-h-80 lg:min-h-[440px] ${index === 1 ? 'lg:order-2' : ''}`}>
            <Image src={product.image} alt={product.alt} fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover transition duration-700 hover:scale-[1.03]" />
            <div className="absolute inset-x-0 bottom-0 flex items-center justify-between gap-3 bg-[#001d2e]/90 px-5 py-4 font-mono text-[10px] uppercase tracking-wider text-white sm:text-xs"><span>{product.detail}</span><span>Smart Steel</span></div>
          </div>
          <div className={`flex flex-col justify-center border-b border-[#cad9e2] py-7 sm:py-9 lg:border-0 lg:px-12 ${index === 1 ? 'lg:order-1 lg:pl-0' : ''}`}>
            <p className={label}>{product.code} / Atlas range</p><h3 className="mt-4 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">{product.title}</h3>
            <p className="mt-5 max-w-lg leading-7 text-[#526878]">{product.description}</p>
            <div className="mt-7"><Link href={product.href} className={action}>{product.cta}<span aria-hidden="true">↗</span></Link></div>
            <Link href={product.product} className="mt-5 inline-flex min-h-11 items-center text-sm font-semibold text-[#0043f3]">Explore the product <span className="ml-3" aria-hidden="true">→</span></Link>
            <div className="mt-6 flex flex-wrap gap-x-5 gap-y-3 border-t border-[#cad9e2] pt-5">{product.links.map(([title, href]) => <Link key={href} href={href} className="text-sm text-[#526878] underline decoration-[#cad9e2] underline-offset-4 hover:text-[#0043f3]">{title}</Link>)}</div>
          </div>
        </article>)}
      </div>
      <div className="mt-10 flex flex-col gap-4 border-b border-[#cad9e2] pb-6 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm leading-6 text-[#526878]">Also in the range: steel carports and solar ground mount structures.</p><Link href="/products" className="inline-flex min-h-11 items-center text-sm font-semibold text-[#0043f3]">View all steel building products ↗</Link></div>
    </section>

    <section className="bg-[#001d2e] px-5 py-16 text-white sm:px-8 lg:py-20" aria-labelledby="scope-heading">
      <div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-2"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#c1d9e5]">Warehouse prices / Know your scope</p><h2 id="scope-heading" className="mt-5 max-w-xl text-3xl font-semibold leading-tight tracking-tight sm:text-5xl">Choose how much<br />of the building you need.</h2></div><div className="lg:pt-8"><p className="max-w-xl leading-7 text-[#c1d9e5]">Compare steel warehouse sizes, prices and supply options. The Atlas guide changes with your dimensions, steel finish and sheeting, so you can compare a defined configuration.</p><Link href="/warehouse-cost" className="mt-6 inline-flex min-h-12 items-center border-b border-white/40 text-sm font-semibold text-white">Compare warehouse cost guides <span className="ml-6" aria-hidden="true">↗</span></Link></div></div>
        <div className="mt-12 grid border-y border-white/20 md:grid-cols-3">{[['01', 'Structure only', 'Steel frame, purlins, bracing and connection hardware.'], ['02', 'Roof sheeted', 'Add roof sheeting to the steel structure for overhead cover.'], ['03', 'Enclosed options', 'Explore wall and gable sheeting in the builder. Confirm openings and doors with your quote.']].map(([number, title, description]) => <div key={number} className="border-b border-white/20 py-7 last:border-b-0 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0"><p className="font-mono text-xs text-[#c1d9e5]">/{number}</p><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/70">{description}</p></div>)}</div>
        <p className="mt-6 max-w-4xl text-sm leading-6 text-[#c1d9e5]">Supply-only guide prices exclude VAT. Foundations, slabs, delivery and installation are reviewed separately. Solar carport guide prices cover the steel structure; solar panels and electrical work are excluded.</p>
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24" aria-labelledby="project-heading">
      <div className="mb-9 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className={label}>On site / Completed Smart Steel work</p><h2 id="project-heading" className="mt-4 text-3xl font-semibold tracking-tight sm:text-5xl">From steel to useful space.</h2></div><Link href="/recent" className="inline-flex min-h-11 items-center font-semibold text-[#0043f3]">View recent projects ↗</Link></div>
      <article className="grid bg-[#f3f7f9] lg:grid-cols-[1.5fr_0.75fr]"><div className="relative min-h-72 sm:min-h-[420px] lg:min-h-[500px]"><Image src="/projects/Solar Carports_Centurion Golf Club/7.webp" alt="Completed solar carport parking at Centurion Golf Club in Gauteng" fill sizes="(min-width: 1024px) 65vw, 100vw" className="object-cover" /></div><div className="flex flex-col justify-end p-7 sm:p-10"><p className={label}>Centurion / Gauteng</p><h3 className="mt-5 text-3xl font-semibold leading-tight">Solar parking at Centurion Golf Club</h3><p className="mt-5 leading-7 text-[#526878]">Covered parking and a steel structure supporting a working solar array. A completed Smart Steel project showing how parking space can become productive infrastructure.</p><Link href="/products/cflc-solar-carports" className="mt-8 inline-flex min-h-11 items-center font-semibold text-[#0043f3]">Explore solar carport structures ↗</Link></div></article>
    </section>

    <section className="border-y border-[#cad9e2] bg-[#f3f7f9] px-5 py-14 sm:px-8 lg:py-16"><div className="mx-auto max-w-7xl"><p className={label}>A clear route to your quote</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Configure. Compare. Confirm.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{[['01', 'Explore in 3D', 'Choose warehouse dimensions and sheeting, or plan your solar carport parking layout.'], ['02', 'Check the guide price', 'Review the selected supply scope and an indicative price excluding VAT.'], ['03', 'Request a reviewed quote', 'Send your configuration so Smart Steel can confirm site requirements, scope and delivery.']].map(([number, title, body]) => <div key={number} className="border-t border-[#cad9e2] pt-5"><span className="font-mono text-sm text-[#0043f3]">{number}</span><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 max-w-sm text-sm leading-7 text-[#526878]">{body}</p></div>)}</div></div></section>

    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:py-20"><div><p className={label}>Beyond the standard range</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">A different brief?<br />Let’s work through it.</h2><p className="mt-5 max-w-sm leading-7 text-[#526878]">Discuss custom dimensions, agricultural uses, roof systems or installation requirements with Smart Steel.</p><Link href="/contact" className="mt-6 inline-flex min-h-11 items-center font-semibold text-[#0043f3]">Talk to Smart Steel ↗</Link></div><div className="border-t border-[#cad9e2]">{[['Custom LSF warehouses', 'Project-specific spans, layouts and warehouse requirements.', '/warehouses/lsf'], ['Steel farm buildings', 'Agricultural storage, equipment cover and operational buildings.', '/steel-farm-buildings'], ['Fabrication and installation', 'Confirm steel supply, delivery and erection for your site.', '/steel-fabrication-installation'], ['Lightweight steel roof trusses', 'Roof structure options and practical pricing guidance.', '/products/lightweight-steel-trusses']].map(([title, body, href]) => <Link key={href} href={href} className="group flex min-h-24 items-center justify-between gap-5 border-b border-[#cad9e2] py-5"><div><h3 className="text-lg font-semibold transition group-hover:text-[#0043f3]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#526878]">{body}</p></div><span className="text-xl text-[#0043f3]" aria-hidden="true">↗</span></Link>)}</div></section>

    <section className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr] lg:pb-24"><div><p className={label}>Before you build</p><h2 className="mt-4 max-w-sm text-3xl font-semibold tracking-tight sm:text-4xl">Your questions,<br />answered.</h2></div><div className="border-t border-[#cad9e2]">{questions.map(item => <details key={item.question} className="group border-b border-[#cad9e2] py-5"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-6 font-semibold marker:content-none">{item.question}<span className="text-xl text-[#0043f3] group-open:rotate-45" aria-hidden="true">+</span></summary><p className="max-w-2xl pt-4 text-sm leading-7 text-[#526878]">{item.answer}</p></details>)}</div></section>

    <section className="bg-[#0043f3] px-5 py-14 text-white sm:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl items-end gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-white/75">Atlas / Your next step</p><h2 className="mt-5 text-4xl font-semibold leading-[1.08] tracking-tight sm:text-5xl">See your structure.<br />Know your starting price.</h2></div><div className="flex flex-col gap-3"><Link href="/warehouse-builder" className="flex min-h-14 items-center justify-between gap-5 bg-white px-6 py-4 font-semibold text-[#0043f3] transition hover:bg-[#c1d9e5]">Build my warehouse in 3D <span aria-hidden="true">↗</span></Link><Link href="/tools/solar-carport-estimator" className="flex min-h-14 items-center justify-between gap-5 border border-white/60 px-6 py-4 font-semibold transition hover:bg-white/10">Build my solar carport in 3D <span aria-hidden="true">↗</span></Link></div></div></section>
  </div>;
}
